FROM jenkins/jenkins:lts

# Install Docker
USER root
RUN apt-get update && \
    apt-get install -y docker.io python3-pip && \
    pip3 install awscli && \
    usermod -aG docker jenkins

USER jenkins
