name: CI/CD Pipeline - Docker to AWS ECR & EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPO_BACKEND: 203783636897.dkr.ecr.us-east-1.amazonaws.com/my-backend-repo
  ECR_REPO_FRONTEND: 203783636897.dkr.ecr.us-east-1.amazonaws.com/my-frontend-repo
  
jobs:
  deploy:
    runs-on: ubuntu-latest #yeh ek linux machine dee ga jahan pipeline chaleggi

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4   # GitHub repo ka code runner machine par copy karta ha

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Verify AWS Login
      run: aws sts get-caller-identity    # aws login successful hai yeh nahi matlb pehle test phir deploy

    - name: Login to Amazon ECR
      run: |    # docker ko ecr say automate karta hai
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_BACKEND
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_FRONTEND

    - name: Build Docker Images
      run: |
        docker build -t my-backend:latest backend/
        docker build -t my-frontend:latest frontend/

    - name: Tag & Push Images to ECR
      run: |
        docker tag my-backend:latest $ECR_REPO_BACKEND:latest
        docker tag my-frontend:latest $ECR_REPO_FRONTEND:latest
        docker push $ECR_REPO_BACKEND:latest
        docker push $ECR_REPO_FRONTEND:latest

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.3
      with: # action ko input dana kau liya 
        host: ${{ secrets.EC2_HOST }}     # ec2 ka public ip 
        username: ${{ secrets.EC2_USER }}  #ec2 ka linux user jo ubuntu rakha hai maina
        key: ${{ secrets.EC2_SSH_KEY }}     # ec2 ka private key .pem   ssh kay login kay liya hai ec2 
        script: |     # yaha se ec2 machine ka andar command run hona hai
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} #ec2 ecr say image pull karna kay liya
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_DEFAULT_REGION=${{ env.AWS_REGION }}

          cd /home/ubuntu/dec  # is directory mai ja raha hai

          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO_BACKEND
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO_FRONTEND

          docker-compose down  # delete old container
          docker-compose pull   #ecr say latest image download ho ge 
          docker-compose up -d    # container background mai start kay ga




